# Generated by Django 6.0.3 on 2026-03-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botiga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videojoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=50)),
                ('preu', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='productes',
        ),
        migrations.AddField(
            model_name='comanda',
            name='videojocs',
            field=models.ManyToManyField(to='botiga.videojoc'),
        ),
        migrations.DeleteModel(
            name='Producte',
        ),
    ]
