# Generated by Django 6.0.3 on 2026-03-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botiga', '0002_videojoc_remove_comanda_productes_comanda_videojocs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojoc',
            name='venudes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videojoc',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
